import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:scrren4/theme_and_components/test_response.dart';
import 'package:toggle_switch/toggle_switch.dart';
import 'package:fl_chart/fl_chart.dart';


class PieScreen extends StatefulWidget {
  PieScreen({super.key});

  @override
  State<PieScreen> createState() => _PieScreenState();
}

class _PieScreenState extends State<PieScreen> {
  var selectedToggleIndex = 0;
  var categoryToggleIndex = 0;
  var simpleToggleIndex = 0;
  Autogenerated? obj;
  void initState() {
    readJson();
    super.initState();

  }
  Future<void> readJson() async {
    final String response = await rootBundle.loadString('assets/test.json');
    obj = Autogenerated.fromJson(json.decode(response));

  }

  @override
  Widget build(BuildContext context) {
    List Kushang = ['Kushang','Kushang'];
    List yourExpenseList = ['You', 'Kumar', 'Ram', 'Raj', 'Kushang'];
    List categoryList = ['fuel', 'food', 'rent', 'others', 'shopping'];
    List expense = ['1000', '2000', '3000', '4000', '5000'];
    return Scaffold(
      backgroundColor: Theme.of(context).colorScheme.surface,
      body: Padding(
        padding: const EdgeInsets.only(top: 16, left: 16, right: 16),
        child: ListView(
          children: [
            Padding(
              padding: const EdgeInsets.only(top: 30, bottom: 30),
              child: Row(
                children: [
                  Text(
                    "Ride Expenses",
                    style: TextStyle(fontSize: 24, fontWeight: FontWeight.w400),
                  ),
                  Spacer(),
                  IconButton(onPressed: (){
                    Navigator.pop(context);
                  }, icon: Icon(Icons.close),)
                ],
              ),
            ),
            // Container for the toggle switch
            Container(
              decoration: BoxDecoration(
                color: Colors.black, // Uniform background for all toggle buttons
              ),
              child: Padding(
                padding: const EdgeInsets.only(bottom: 8.0),
                child: ToggleSwitch(
                  cornerRadius: 0,
                  initialLabelIndex: selectedToggleIndex,
                  activeBorders: [
                    Border(
                      bottom: BorderSide(
                        color: Theme.of(context).colorScheme.primary,
                        width: 2,
                      ),
                    )
                  ],
                  minWidth: MediaQuery.of(context).size.width / 3, // Split evenly for 3 buttons
                  minHeight: 40,
                  activeBgColor: [Colors.black],
                  activeFgColor: Theme.of(context).colorScheme.primary,
                  inactiveBgColor: Colors.black,
                  inactiveFgColor: Colors.white,
                  totalSwitches: 3,
                  labels: ['Common', 'Individual', 'Only Me'],
                  onToggle: (index) {
                    setState(() {
                      selectedToggleIndex = index!;
                    });
                  },
                ),
              ),
            ),

            if(selectedToggleIndex == 0) ...[
              Padding(
                padding: const EdgeInsets.only(top: 30, bottom: 30),
                child: Container(
                    decoration: BoxDecoration(border: Border.all(color: Color(0x34ffffff),width: 1),borderRadius: BorderRadius.circular(20)),
                    child:

                    Padding(
                      padding: const EdgeInsets.all(20),
                      child: Column(
                        children: [
                          Container(height: 200,
                            width: 200,
                            child: Container(

                              child: PieChart(
                                  PieChartData(
                                    sections: [
                                      PieChartSectionData(
                                        gradient: LinearGradient(colors: [Color(0xffFFC700),Color(0xff997700)]),
                                        value: 25,
                                        title: '',

                                        radius: 20,
                                        titleStyle: TextStyle(
                                          fontSize: 16,
                                          fontWeight: FontWeight.bold,
                                          color: Theme.of(context).colorScheme.onPrimary,
                                        ),
                                      ),
                                      PieChartSectionData(
                                        gradient:
                                        LinearGradient(
                                            begin: Alignment.centerLeft,
                                            end: Alignment.centerRight,

                                            colors: [Color(0xFFDD6762),Color(0xFFDD695E).withOpacity(0.8)]),
                                        value: 12.5,
                                        title: '',

                                        radius: 20,
                                        titleStyle: TextStyle(
                                          fontSize: 16,
                                          fontWeight: FontWeight.bold,
                                          color: Theme.of(context).colorScheme.onPrimary,
                                        ),
                                      ),
                                      PieChartSectionData(
                                        gradient: LinearGradient(colors: [Color(0xFFEB2EEF),Color(0xFFEB2EEF).withOpacity(0.7)]),
                                        value: 12.5,
                                        title: '',

                                        radius: 20,
                                        titleStyle: TextStyle(
                                          fontSize: 16,
                                          fontWeight: FontWeight.bold,
                                          color: Theme.of(context).colorScheme.onPrimary,
                                        ),
                                      ),
                                      PieChartSectionData(
                                        gradient: LinearGradient(colors: [Color(0xff1993F6),Color(0xff0F5690)]) ,
                                        value: 25,
                                        title: '',

                                        radius: 20,
                                        titleStyle: TextStyle(
                                          fontSize: 16,
                                          fontWeight: FontWeight.bold,
                                          color: Theme.of(context).colorScheme.onSecondary,
                                        ),
                                      ),
                                      PieChartSectionData(
                                        gradient: LinearGradient(colors: [Color(0xff42CFA3),Color(0xff216953)]) ,
                                        value: 25,
                                        title: '',


                                        radius: 20,
                                        titleStyle: TextStyle(
                                          fontSize: 16,
                                          fontWeight: FontWeight.bold,
                                          color: Theme.of(context).colorScheme.onError,
                                        ),
                                      ),
                                    ],
                                  )
                              ),
                            ),
                          ),
                          SizedBox(height: 20),
                          Row(
                            children: [

                              SizedBox(height: 25,
                                width: 45,
                                child: ToggleSwitch(
                                  initialLabelIndex: simpleToggleIndex,

                                  labels: ['', ''],
                                  activeBgColor: [Colors.white],
                                  inactiveBgColor: Colors.black,
                                  borderColor: [Color(0x32ffffff)],

                                  cornerRadius: 100,
                                  radiusStyle: true,
                                  onToggle: (index) {
                                    setState(() {
                                      simpleToggleIndex = index!;
                                    });
                                  },
                                ),
                              ),
                              SizedBox(width: 10),
                              Text("Category")
                            ],
                          ),
                          Padding(
                            padding: const EdgeInsets.only(top: 20.0,bottom: 20.0),
                            child: SingleChildScrollView(
                              scrollDirection: Axis.horizontal,
                              child: Row(mainAxisAlignment: MainAxisAlignment.center,

                                children: [
                                  Container(
                                    decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xffFFC700),Color(0xff997700)]),borderRadius: BorderRadius.circular(4)),
                                    height: 30,

                                    child: Padding(
                                      padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                                      child: Text("YOU",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                                    ),
                                  ),
                                  SizedBox(width: 10,)
                                  ,Container(
                                    decoration: BoxDecoration(
                                        gradient:
                                        LinearGradient(
                                            begin: Alignment.centerLeft,
                                            end: Alignment.centerRight,

                                            colors: [Color(0xFFDD6762),Color(0xFFDD695E).withOpacity(0.8)]),borderRadius: BorderRadius.circular(4)),
                                    height: 30,

                                    child: Padding(
                                      padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                                      child: Text("Kumar",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                                    ),
                                  ),SizedBox(width: 10,),Padding(
                                    padding: const EdgeInsets.only(right: 15.0),
                                    child: Container(
                                      decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xFFEB2EEF),Color(0xFFEB2EEF).withOpacity(0.7)]) ,borderRadius: BorderRadius.circular(4)),
                                      height: 30,

                                      child: Padding(
                                        padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                                        child: Text("Ram",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                                      ),
                                    ),
                                  ),Padding(
                                    padding: const EdgeInsets.only(right: 15.0),
                                    child: Container(
                                      decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff42CFA3),Color(0xff216953)]) ,borderRadius: BorderRadius.circular(4)),
                                      height: 30,

                                      child: Padding(
                                        padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                                        child: Text("Raj",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                                      ),
                                    ),
                                  ),Padding(
                                    padding: const EdgeInsets.only(right: 15.0),
                                    child: Container(
                                      decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff1993F6),Color(0xff0F5690)]) ,borderRadius: BorderRadius.circular(4)),
                                      height: 30,

                                      child: Padding(
                                        padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                                        child: Text("Kushang",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                                      ),
                                    ),
                                  )
                                ],
                              ),
                            ),

                          ),

                        ],
                      ),
                    )



                ),
              ),

//vie summary button
              Padding(

                padding: const EdgeInsets.only(bottom: 30),
                child: Container(decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5b5b5b),Color(
                    0xff333131)]),borderRadius: BorderRadius.circular(40)),

                  child: ElevatedButton(onPressed: (){

                    _modalBottomSheetMenu();


                  }, child: Text("View Summary",style: TextStyle(color: Colors.white),)
                    ,style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.transparent,
                      minimumSize: Size(MediaQuery.of(context).size.width, 50),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(40),
                      ),
                    ),),
                ),
              ),

              Padding(
                padding: const EdgeInsets.only(bottom: 30),
                child: Row(
                  children: [
                    Text(
                      "Individual Expenses",
                      style: TextStyle(fontSize: 24, fontWeight: FontWeight.w400),
                    ),
                    Spacer(),
                    Icon(Icons.sort),
                  ],
                ),
              ),


              Row(
                children: [
                  Container(
                    decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5B5B5B),Color(0xff333131)]),borderRadius: BorderRadius.circular(4)),
                    height: 30,

                    child: Padding(
                      padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                      child: Row(
                        children: [
                          Text("Ram",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                          SizedBox(width: 5,),
                          Icon(Icons.close,size: 18,)
                        ],
                      ),
                    ),

                  ),SizedBox(width: 10,),Container(
                    decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5B5B5B),Color(0xff333131)]),borderRadius: BorderRadius.circular(4)),
                    height: 30,

                    child: Padding(
                      padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                      child: Row(
                        children: [
                          Text("Kushang",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                          SizedBox(width: 5,),
                          Icon(Icons.close,size: 18,)
                        ],
                      ),
                    ),
                  ),
                  SizedBox(width: 10,),
                  Container(
                    decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5B5B5B),Color(0xff333131)]),borderRadius: BorderRadius.circular(4)),
                    height: 30,

                    child: Padding(
                      padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                      child: Row(
                        children: [
                          Text("Fuel",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                          SizedBox(width: 5,),
                          Icon(Icons.close,size: 18,)
                        ],
                      ),
                    ),
                  ),
                ],
              ),

              Padding(
                padding: const EdgeInsets.only(top: 10,bottom: 10),
                child: Container(
                  child: ListTile(
                    tileColor:  Color(0x1affffff),


                    title: Row(
                      children: [
                        Expanded(child: Text("Kushang",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),)),
                        Text("₹ 5000", style: TextStyle(color: Theme.of(context).colorScheme.onPrimary)),
                      ],
                    ),
                    subtitle: Row(


                      children: [
                        Expanded(child: Text("Fuel", style: TextStyle(color: Theme.of(context).colorScheme.secondary))),

                        Text("3:00 pm", style: TextStyle(color: Theme.of(context).colorScheme.secondary)),
                      ],


                    ),
                  ),
                ),
              ),


              Padding(
                padding: const EdgeInsets.only(top: 10,bottom: 10),
                child: ListTile(
                  tileColor:  Color(0x1affffff),


                  title: Row(
                    children: [
                      Expanded(child: Text("Kushang",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),)),
                      Text("₹ 5000", style: TextStyle(color: Theme.of(context).colorScheme.onPrimary)),
                    ],
                  ),
                  subtitle: Row(


                    children: [
                      Expanded(child: Text("Food", style: TextStyle(color: Theme.of(context).colorScheme.secondary))),

                      Text("3:00 pm", style: TextStyle(color: Theme.of(context).colorScheme.secondary)),
                    ],


                  ),
                ),
              ),


            ] else if(selectedToggleIndex == 1) ...[
              Column(
                children: [
                  Padding(
                    padding: const EdgeInsets.only(top: 30, bottom: 30),
                    child: Container(
                        decoration: BoxDecoration(border: Border.all(color: Color(0x34ffffff),width: 1),borderRadius: BorderRadius.circular(20)),
                        child:

                        Padding(
                          padding: const EdgeInsets.all(20),
                          child: Column(
                            children: [
                              Container(height: 200,
                                width: 200,
                                child: Container(

                                  child: PieChart(
                                      PieChartData(
                                        sections: [
                                          PieChartSectionData(
                                            gradient: LinearGradient(colors: [Color(0xffFFC700),Color(0xff997700)]),
                                            value: 25,
                                            title: '',

                                            radius: 20,
                                            titleStyle: TextStyle(
                                              fontSize: 16,
                                              fontWeight: FontWeight.bold,
                                              color: Theme.of(context).colorScheme.onPrimary,
                                            ),
                                          ),
                                          PieChartSectionData(
                                            gradient:
                                            LinearGradient(
                                                begin: Alignment.centerLeft,
                                                end: Alignment.centerRight,

                                                colors: [Color(0xFFDD6762),Color(0xFFDD695E).withOpacity(0.8)]),
                                            value: 12.5,
                                            title: '',

                                            radius: 20,
                                            titleStyle: TextStyle(
                                              fontSize: 16,
                                              fontWeight: FontWeight.bold,
                                              color: Theme.of(context).colorScheme.onPrimary,
                                            ),
                                          ),
                                          PieChartSectionData(
                                            gradient: LinearGradient(colors: [Color(0xFFEB2EEF),Color(0xFFEB2EEF).withOpacity(0.7)]),
                                            value: 12.5,
                                            title: '',

                                            radius: 20,
                                            titleStyle: TextStyle(
                                              fontSize: 16,
                                              fontWeight: FontWeight.bold,
                                              color: Theme.of(context).colorScheme.onPrimary,
                                            ),
                                          ),
                                          PieChartSectionData(
                                            gradient: LinearGradient(colors: [Color(0xff1993F6),Color(0xff0F5690)]) ,
                                            value: 25,
                                            title: '',

                                            radius: 20,
                                            titleStyle: TextStyle(
                                              fontSize: 16,
                                              fontWeight: FontWeight.bold,
                                              color: Theme.of(context).colorScheme.onSecondary,
                                            ),
                                          ),
                                          PieChartSectionData(
                                            gradient: LinearGradient(colors: [Color(0xff42CFA3),Color(0xff216953)]) ,
                                            value: 25,
                                            title: '',


                                            radius: 20,
                                            titleStyle: TextStyle(
                                              fontSize: 16,
                                              fontWeight: FontWeight.bold,
                                              color: Theme.of(context).colorScheme.onError,
                                            ),
                                          ),
                                        ],
                                      )
                                  ),
                                ),
                              ),
                              Padding(
                                padding: const EdgeInsets.only(top: 20.0,bottom: 20.0),
                                child: SingleChildScrollView(
                                  scrollDirection: Axis.horizontal,
                                  child: Row(mainAxisAlignment: MainAxisAlignment.center,

                                    children: [
                                      Container(
                                        decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xffFFC700),Color(0xff997700)]),borderRadius: BorderRadius.circular(4)),
                                        height: 30,

                                        child: Padding(
                                          padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                                          child: Text("YOU",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                                        ),
                                      ),
                                      SizedBox(width: 10,)
                                      ,Container(
                                        decoration: BoxDecoration(
                                            gradient:
                                            LinearGradient(
                                                begin: Alignment.centerLeft,
                                                end: Alignment.centerRight,

                                                colors: [Color(0xFFDD6762),Color(0xFFDD695E).withOpacity(0.8)]),borderRadius: BorderRadius.circular(4)),
                                        height: 30,

                                        child: Padding(
                                          padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                                          child: Text("Kumar",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                                        ),
                                      ),SizedBox(width: 10,),Padding(
                                        padding: const EdgeInsets.only(right: 15.0),
                                        child: Container(
                                          decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xFFEB2EEF),Color(0xFFEB2EEF).withOpacity(0.7)]) ,borderRadius: BorderRadius.circular(4)),
                                          height: 30,

                                          child: Padding(
                                            padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                                            child: Text("Ram",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                                          ),
                                        ),
                                      ),Padding(
                                        padding: const EdgeInsets.only(right: 15.0),
                                        child: Container(
                                          decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff42CFA3),Color(0xff216953)]) ,borderRadius: BorderRadius.circular(4)),
                                          height: 30,

                                          child: Padding(
                                            padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                                            child: Text("Raj",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                                          ),
                                        ),
                                      ),Padding(
                                        padding: const EdgeInsets.only(right: 15.0),
                                        child: Container(
                                          decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff1993F6),Color(0xff0F5690)]) ,borderRadius: BorderRadius.circular(4)),
                                          height: 30,

                                          child: Padding(
                                            padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                                            child: Text("Kushang",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                                          ),
                                        ),
                                      )
                                    ],
                                  ),
                                ),

                              ),
                              Row(mainAxisSize: MainAxisSize.min,mainAxisAlignment: MainAxisAlignment.center,crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  ToggleSwitch(

                                    minWidth: 93.0,

                                    //customWidths: const [93,93],


                                    radiusStyle: true,
                                    labels: ['Person','Category'],
                                    initialLabelIndex: 0,
                                    cornerRadius: 4,
                                    activeFgColor: Colors.white,
                                    inactiveFgColor: Colors.white,
                                    activeBgColors: [
                                      [Color(0xffEB1D23), Color(0xff840004),], // Gradient for Active
                                      [Color(0xffEB1D23), Color(0xff840004),],  // Gradient for Inactive
                                    ],
                                    inactiveBgColor: Color(0x47292424),


                                    onToggle: (index) {
                                      setState(() {
                                        categoryToggleIndex = index!;
                                      });
                                    },
                                  ),
                                ],
                              )
                            ],
                          ),
                        )



                    ),
                  ),

                        ElevatedButton(onPressed: (){

                        }, child:Padding(
                        padding: const EdgeInsets.only(bottom: 20),
                        child: Container(decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5b5b5b),Color(
                        0xff333131)]),borderRadius: BorderRadius.circular(40)),

                        child: ElevatedButton(onPressed: (){

                        _modalBottomSheetMenu();


                        }, child: Text("View Summary",style: TextStyle(color: Colors.white),)
                        ,style: ElevatedButton.styleFrom(
                        backgroundColor: Colors.transparent,
                        minimumSize: Size(MediaQuery.of(context).size.width, 50),
                        shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(40),
                                                        ),
                                                        ),),
                                                        ),
                                                        ),),
                  Row(
                    children: [
                      Text(
                        "Individual Expenses",
                        style: TextStyle(fontSize: 24, fontWeight: FontWeight.w400),
                      ),
                      Spacer(),
                      Icon(Icons.sort),
                    ],
                  ),


                  Padding(
                    padding: const EdgeInsets.only(top: 20),
                    child: Row(
                      children: [
                        Container(
                          decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5B5B5B),Color(0xff333131)]),borderRadius: BorderRadius.circular(4)),
                          height: 30,

                          child: Padding(
                            padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                            child: Row(
                              children: [
                                Text("Ram",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                                SizedBox(width: 5,),
                                Icon(Icons.close,size: 18,)
                              ],
                            ),
                          ),

                        ),SizedBox(width: 10,),Container(
                          decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5B5B5B),Color(0xff333131)]),borderRadius: BorderRadius.circular(4)),
                          height: 30,

                          child: Padding(
                            padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                            child: Row(
                              children: [
                                Text("Kushang",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                                SizedBox(width: 5,),
                                Icon(Icons.close,size: 18,)
                              ],
                            ),
                          ),
                        ),
                        SizedBox(width: 10,),
                        Container(
                          decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5B5B5B),Color(0xff333131)]),borderRadius: BorderRadius.circular(4)),
                          height: 30,

                          child: Padding(
                            padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                            child: Row(
                              children: [
                                Text("Fuel",style: TextStyle(color: Theme.of(context).colorScheme.onPrimary),),
                                SizedBox(width: 5,),
                                Icon(Icons.close,size: 18,)
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.only(top: 20,bottom: 10),
                    child: Row(children: [
                      Expanded(child: Text("23 Apr 2024",style: TextStyle(fontSize: 12),)),
                      Text("₹ 5000",style: TextStyle(fontSize: 12,color: Color(0xffffffff)),)

                    ],


                    ),
                  ),
                  Container(
                    height: 300,
                    child: ListView.builder(itemCount: 2,itemBuilder: (context,index){
                      return Padding(
                        padding: const EdgeInsets.only(top: 10,bottom: 10),
                        child: Container(
                          width: 380,
                          decoration: BoxDecoration(color: Color(0x1affffff),borderRadius: BorderRadius.circular(10)),
                          child: ListTile(
                            title: Row(
                              children: [
                                Expanded(child: Text("${Kushang[index]}",style: TextStyle(color: Colors.white, fontWeight: FontWeight.w400,fontSize: 24))),
                                Text("₹${expense[index]}",style: TextStyle(color: Theme.of(context).colorScheme.primary,fontSize: 20, fontWeight: FontWeight.w400))
                              ],

                            ),subtitle: Row(
                              children: [Expanded(child: Text("${categoryList[index]}",style: TextStyle(color: Color(0x80ffffff), fontWeight: FontWeight.w400,fontSize: 18))),
                                Text("₹${expense[index]}",style: TextStyle(color: Color(0x80ffffff), fontWeight: FontWeight.w400,fontSize: 18))]

                          ),
                          ),
                        ),
                      );


                    }




                    ),
                  )
                ],
              ),


            ]else ...[

                    Column(
                      children: [
                        Padding(
                        padding: const EdgeInsets.only(top: 30, bottom: 30),
                        child: Container(
                        decoration: BoxDecoration(border: Border.all(color: Color(0x34ffffff),width: 1),borderRadius: BorderRadius.circular(20)),
                        child:

                        Padding(
                        padding: const EdgeInsets.all(20),
                        child: Column(
                        children: [
                        Container(height: 200,
                        width: 200,
                        child: Container(

                        child: PieChart(
                            PieChartData(
                            sections: [
                            PieChartSectionData(
                            gradient: LinearGradient(colors: [Color(0xffFFC700),Color(0xff997700)]),
                            value: 75,
                            title: '',

                            radius: 20,
                            titleStyle: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                            color: Theme.of(context).colorScheme.onPrimary,
                            ),
                            ),
                            PieChartSectionData(
                            gradient:
                            LinearGradient(
                            begin: Alignment.centerLeft,
                            end: Alignment.centerRight,

                            colors: [Color(0xFFDD6762),Color(0xFFDD695E).withOpacity(0.8)]),
                            value: 25,
                            title: '',

                            radius: 20,
                            titleStyle: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                            color: Theme.of(context).colorScheme.onPrimary,
                            ),
                            ),]
                            )
                        )
                        )
                        ),
                          Padding(
                            padding: const EdgeInsets.only(top: 20.0,bottom: 20.0),
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Container(
                                  height: 30,
                                    decoration:BoxDecoration(gradient:LinearGradient(colors: [Color(0xffFFC700),Color(0xff997700)]),borderRadius: BorderRadius.circular(4)),
                            child: Padding(
                              padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                              child: Text("Spent"),
                            )),
                                SizedBox(width: 10),

                                  Container(
                                    height: 30,
                                    decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xFFDD6762),Color(0xFFDD695E).withOpacity(0.8)]),borderRadius: BorderRadius.circular(4)),
                                      child:
                                      Padding(
                                          padding: const EdgeInsets.only(left: 10.0,right: 10.0,top: 6.0,bottom: 6.0),
                                          child: Text("Borrow")),
                                )
                              ],
                            ),
                          )
                        ]
                        )
                        )
                        )
                        ),


                        Container(
                          width: 380,
                          decoration: BoxDecoration(
                            border: Border.all(color: Color(0x32ffffff)),
                              gradient: LinearGradient(colors: [Color(0x5b5b5b),Color(0xff5B5B5B),]),borderRadius: BorderRadius.circular(10)),

                          child: Row(
                            children: [
                              Padding(
                                padding: const EdgeInsets.all(10.0),
                                child: Text("Your Balance:",style: TextStyle(color: Colors.white,fontSize: 16,fontWeight: FontWeight.w500),),
                              ),
                              SizedBox(width: 5),
                              Padding(
                                padding: const EdgeInsets.only(top: 10,bottom:10 ),
                                child: Text("₹ 1000",style: TextStyle(color: Theme.of(context).colorScheme.primary,fontSize: 16),),
                              ),Spacer(),
                              Padding(
                                padding: const EdgeInsets.only(right: 10),
                                child: Text("Yet to pay",style: TextStyle(color: Color(
                                    0x80ffffff)),),
                              )
                            ],
                          ),
                        ),

                        Padding(
                          padding: const EdgeInsets.only(top: 15,bottom: 30),
                          child: ElevatedButton(onPressed: (){

                          }, child:Padding(
                              padding: const EdgeInsets.only(bottom: 30),
                              child: Container(decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(0xff5b5b5b),Color(
                              0xff333131)]),borderRadius: BorderRadius.circular(40)),

                              child: ElevatedButton(onPressed: (){

                              _modalBottomSheetMenu();


                              }, child: Text("View Summary",style: TextStyle(color: Colors.white),)
                              ,style: ElevatedButton.styleFrom(
                              backgroundColor: Colors.transparent,
                              minimumSize: Size(MediaQuery.of(context).size.width, 50),
                              shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(40),
                              ),
                              ),),
                              ),
                              ),),
                        ),
                        Padding(
                          padding: const EdgeInsets.only(bottom: 30),
                          child: Row(
                            children: [
                              Text(
                                "Your Expenses",
                                style: TextStyle(fontSize: 24, fontWeight: FontWeight.w400),
                              ),
                              Spacer(),
                              Icon(Icons.sort),
                            ],
                          ),
                        ),

                        Container(
                          height: 300,
                          child: ListView.builder(itemCount: yourExpenseList.length,itemBuilder: (context,index){
                            return Padding(
                              padding: const EdgeInsets.only(top: 10,bottom: 10),
                              child: Container(
                                width: 380,
                                decoration: BoxDecoration(color: Color(0x1affffff),borderRadius: BorderRadius.circular(10)),
                                child: ListTile(
                                title: Row(
                                children: [
                                Expanded(child: Text("${yourExpenseList[index]}",style: TextStyle(color: Colors.white, fontWeight: FontWeight.w400,fontSize: 24))),
                                Text("₹${expense[index]}",style: TextStyle(color: Theme.of(context).colorScheme.primary,fontSize: 20, fontWeight: FontWeight.w400))
                                  ],

                                  ),subtitle: Row(
                                    children: [Expanded(child: Text("${categoryList[index]}",style: TextStyle(color: Color(0x80ffffff), fontWeight: FontWeight.w400,fontSize: 18))),
                                    Text("₹${expense[index]}",style: TextStyle(color: Color(0x80ffffff), fontWeight: FontWeight.w400,fontSize: 18))]

                                ),
                                  ),
                              ),
                            );
                          
                          
                                                }

                          
                          
                          
                          ),
                        )],
                    )
            ]



            ],







        ),
      ),
    );
  }
  void _modalBottomSheetMenu(){
    String text = "Summary";
    showModalBottomSheet(
        context: context,
        builder: (builder){
          return  Container(
            child: Column(

              children:[
                Padding(
                padding: const EdgeInsets.only(top: 30, bottom: 30,left: 10,right: 10),
                child: Row(
                  children: [
                    Text(
                     "${text}",
                      style: TextStyle(fontSize: 24, fontWeight: FontWeight.w400),
                    ),
                    Spacer(),
                    IconButton(onPressed: (){
                      Navigator.pop(context);
                    }, icon: Icon(Icons.close),)
                  ],
                ),
              ),
          Expanded(
            child: ListView.builder(itemCount: obj!.maindata!.length,itemBuilder: (context,index){
              return Padding(
                padding: const EdgeInsets.only(left: 16.0,right: 16.0,bottom: 5),
                child: Container(
                  color: Color(0x1affffff),
                  child: Theme(
                      data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
                      child: ExpansionTile(
            
            
                          title: Row(
                            children: [
            
                              Expanded(child: Text(obj!.maindata![index].name!,style: TextStyle(color: Theme.of(context).colorScheme.onPrimary,fontWeight: FontWeight.w500),)),
                              Text("₹ ${obj!.maindata![index].amount!}", style: TextStyle(color: Colors.green,fontWeight: FontWeight.w500)),
                            ],
                          ), children: [
            for(var subIndex = 0; subIndex <obj!.maindata![index].subdata!.length; subIndex++)
                      ListTile(
                        title: Row(
                          children: [
                            Icon(Icons.local_gas_station_outlined), SizedBox(width: 7),
                            Expanded(child: Text(
                                "${obj!.maindata![index].subdata![subIndex].heading!}",
                                style: TextStyle(
                                    color: Colors.white, fontWeight: FontWeight.w400))),
                            Text("${obj!.maindata![index].subdata![subIndex].subamount!}",
                                style: TextStyle(
                                    color: Colors.white, fontWeight: FontWeight.w400))
                          ],
                        ),
                      ),
                      ]
                      )),
                ),
              );
            }),
          ),
              ]));}

    );}

  }

