import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:scrren4/theme_and_components/test_response.dart';
import 'package:percent_indicator/percent_indicator.dart';
import 'package:toggle_switch/toggle_switch.dart';

class Progressbar extends StatefulWidget {
  const Progressbar({super.key});

  @override
  State<Progressbar> createState() => _ProgressbarState();
}

class _ProgressbarState extends State<Progressbar> {
  Autogenerated? obj;
  double total = 0;
  Color getColorForName(String name) {
    switch (name) {
      case 'Kushang':
        return Colors.red;
      case 'Deepthi':
        return Colors.orange;
      case 'Ram':
        return Colors.green;
      case 'khalil':
        return Colors.blue;
      case 'mahesh':
        return Colors.purple;
      default:
        return Colors.grey;
    }
  }

  void initState() {
    readjson();
    super.initState();

  }

  Future<void> readjson() async {
    final String response = await rootBundle.loadString('assets/test.json');
    final data = await json.decode(response);
    obj = Autogenerated.fromJson(data);

    print("obj -- ${obj}");
    if (obj?.maindata != null) {
      double subtotal = 0;
      for (var entry in obj!.maindata!) {
        print("amount -- ${entry.amount}");
        subtotal += entry.amount as double;
      }
      setState(() {
        total = subtotal;
      });
    } else {
      print('maindata is null');
    }
  }




  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.only(top:16, left: 16, right: 16),
        child: ListView(
            children: [
        Padding(
        padding: const EdgeInsets.only(top: 30, bottom: 30),
        child: Row(
          children: [
            Text(
              "Ride Expenses",
              style: TextStyle(fontSize: 24, fontWeight: FontWeight.w400),
            ),
            Spacer(),
            IconButton(onPressed: (){
              Navigator.pop(context);
            }, icon: Icon(Icons.close),)
          ],
        ),),
              Container(
                decoration: BoxDecoration(border: Border.all(color: Color(0x34ffffff)),borderRadius: BorderRadius.circular(10),gradient: LinearGradient(
                  begin: Alignment.topCenter,
                    end: Alignment.bottomCenter,
                    colors: [Color(0xff1E1E1E),Color(0xff000000),])),
                width: 380,
                child: Padding(
                  padding: const EdgeInsets.all(20.0),
                  child: Column(
                    children: [
                      Center(child: Text("₹ ${total}",style: TextStyle(fontSize: 36),)),

                      Text("Total Expenses",style: TextStyle(fontSize: 18,fontWeight: FontWeight.w400,color: Color(0x99ffffff)),),
                      SizedBox(height: 30,),
                      // LinearPercentIndicator(
                      //   barRadius: Radius.circular(10),
                      //   lineHeight: 10,
                      //   linearGradient: LinearGradient(colors: [
                      //     Colors.red, // Kushang's part
                      //     Colors.orange, // Khalil's part
                      //     Colors.green, // Ram's part
                      //     Colors.blue,  // Raj's part
                      //   ],stops: [
                      //     0.25, // Kushang's part
                      //     0.5, // Khalil's part
                      //     0.75, // Ram's part
                      //     1.0, // Raj's part
                      //   ]),
                      //   animation: true,
                      //   animationDuration: 2000,
                      //   percent: 1,
                      //
                      //
                      //
                      // ),
                      ClipRRect(
                        borderRadius: BorderRadius.circular(10),
                        child: Container(
                          decoration: BoxDecoration(borderRadius: BorderRadius.circular(10)),
                          child: Row(
                            children: obj!.maindata!.map((entry){
                              double percentage = entry.amount!.toDouble();
                              return Expanded(
                                flex: (percentage*100).round(),
                                child: Container(
                                  decoration: BoxDecoration(



                                    color: getColorForName(entry.name!),
                                  ),
                                  height: 10,

                                ),
                              );

                          }).toList()

                          ),
                        ),
                      ),
                      SingleChildScrollView(
                        scrollDirection: Axis.horizontal,
                        child: Row(
                          children: [
                            for (int index = 0; index < obj!.maindata!.length; index++)
                              Padding(
                                padding: const EdgeInsets.all(10),
                                child: Container(

                                  decoration: BoxDecoration(color: Color(
                                      0x1affffff),border: Border.all(color: Color(
                                      0x33ffffff)),borderRadius: BorderRadius.circular(10)),
                                  child: Center(
                                    child: Padding(
                                      padding: const EdgeInsets.all(10),
                                      child: Column(
                                        children: [
                                          Text("${obj!.maindata![index].name}", style: TextStyle(fontSize: 12, fontWeight: FontWeight.w400),),
                                          Text("₹${obj!.maindata![index].amount}", style: TextStyle(fontSize: 18, fontWeight: FontWeight.w400),),
                                        ],
                                      ),
                                    ),
                                  ),
                                ),
                              )

                          ],
                        ),
                      ),]
                      ),
                )



                ),Padding(
                  padding: const EdgeInsets.only(top: 30.0),
                  child: Container(
                  width: 380,
                  decoration: BoxDecoration(
                      border: Border.all(color: Color(0x32ffffff)),
                      gradient: LinearGradient(colors: [Color(0x5b5b5b),Color(
                          0x805b5b5b),]),borderRadius: BorderRadius.circular(10)),

                  child: Row(
                    children: [
                      Padding(
                        padding: const EdgeInsets.all(10.0),
                        child: Text("Your Balance:",style: TextStyle(color: Colors.white,fontSize: 16,fontWeight: FontWeight.w500),),
                      ),
                      SizedBox(width: 5),
                      Padding(
                        padding: const EdgeInsets.only(top: 10,bottom:10 ),
                        child: Text("₹ 1000",style: TextStyle(color: Theme.of(context).colorScheme.primary,fontSize: 16,fontWeight: FontWeight.w500),),
                      ),Spacer(),
                      Padding(
                        padding: const EdgeInsets.only(right: 10),
                        child: Text("Yet to pay",style: TextStyle(color: Color(
                            0x80ffffff)),),
                      )
                    ],
                  ),
                                ),
                ),

              Padding(
                padding: const EdgeInsets.only(top: 15.0,bottom: 30),
                child: Container(
                  decoration: BoxDecoration(gradient: LinearGradient(colors: [Color(
                      0x4dd9d9d9),Color(0x1ad9d9d9),]),borderRadius: BorderRadius.circular(40)),
                  child:
                  ElevatedButton(onPressed: (){},style: ElevatedButton.styleFrom(backgroundColor: Colors.transparent), child: Text(("View Summary"),style: TextStyle(color:Colors.white,fontSize: 12,fontWeight: FontWeight.w400),)),
                ),
              ),
              Text("Expenses for this ride",style: TextStyle(fontSize: 24,fontWeight: FontWeight.w400),),

              Padding(
                padding: const EdgeInsets.only(top: 30,bottom: 30),
                child: Container(
                  child: Row(
                    children: [
                      Container(
                          decoration:BoxDecoration(gradient: LinearGradient(begin: Alignment.centerLeft,end: Alignment.centerRight,colors: [Color(0xffEB1D23),Color(0xff840004),]),borderRadius: BorderRadius.circular(40)),
                  child: ElevatedButton(onPressed: (){},style: ElevatedButton.styleFrom(backgroundColor: Colors.transparent),
                                        child: Text("All",style: TextStyle(color: Colors.white),))),
                      SizedBox(width: 10,),

                      Container(
                          decoration: BoxDecoration(gradient: LinearGradient(colors:[Color(0x805b5b5b),Color(0x535353),]),borderRadius: BorderRadius.circular(40)),
                          child: ElevatedButton(onPressed: (){},style: ElevatedButton.styleFrom(backgroundColor: Colors.transparent),
                                                child: Text("Only me",style: TextStyle(color: Colors.white),))),

                    ],
                  ),
                ),
              ),
              
              Row(
                children: [
                  Expanded(child: Text("23 Apr 2024",style: TextStyle(fontSize: 12,fontWeight: FontWeight.w400),)),
                  Text("₹ ${total}")
                ],
              ),
              Container(
                width: 380,
                child: ListView.builder(
                itemCount: obj?.maindata?.length,
                shrinkWrap: true,
                  itemBuilder: (context, index) {
                    return Padding(
                      padding: const EdgeInsets.only(top: 10.0,bottom: 10.0),
                      child: Container(
                        decoration: BoxDecoration(color: Color(0x1affffff),borderRadius: BorderRadius.circular(10)),
                        child: ListTile(
                          title: Row(
                            children: [
                              Expanded(child: Text("${obj!.maindata![index].name}")),
                              Text("₹ ${obj!.maindata![index].amount}"),
                            ],
                          ),
                          subtitle: Column(
                            children: [
                               Row(
                                children: [
                                  Expanded(child: Text("${obj!.maindata![index].subdata![0].heading}")),
                                  Text("₹ ${obj!.maindata![index].subdata![0].subamount}"),
                                ],
                              )])),
                      ),
                    );
                    }))]),
                      ),
                    );
                  }





}
