class Autogenerated {
  List<Maindata>? maindata;

  Autogenerated({this.maindata});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['maindata'] != null) {
      maindata = <Maindata>[];
      json['maindata'].forEach((v) {
        maindata!.add(new Maindata.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.maindata != null) {
      data['maindata'] = this.maindata!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Maindata {
  String? name;
  int? amount;
  List<Subdata>? subdata;

  Maindata({this.name, this.amount, this.subdata});

  Maindata.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    amount = json['amount'];
    if (json['subdata'] != null) {
      subdata = <Subdata>[];
      json['subdata'].forEach((v) {
        subdata!.add(new Subdata.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['amount'] = this.amount;
    if (this.subdata != null) {
      data['subdata'] = this.subdata!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Subdata {
  String? heading;
  int? subamount;

  Subdata({this.heading, this.subamount});

  Subdata.fromJson(Map<String, dynamic> json) {
    heading = json['heading'];
    subamount = json['subamount'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['heading'] = this.heading;
    data['subamount'] = this.subamount;
    return data;
  }
}
